package org.vahcuengh.sawloih.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.vahcuengh.sawloih.model.dao.WordItem;

import org.vahcuengh.sawloih.model.dao.WordItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordItemDaoConfig;

    private final WordItemDao wordItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordItemDaoConfig = daoConfigMap.get(WordItemDao.class).clone();
        wordItemDaoConfig.initIdentityScope(type);

        wordItemDao = new WordItemDao(wordItemDaoConfig, this);

        registerDao(WordItem.class, wordItemDao);
    }
    
    public void clear() {
        wordItemDaoConfig.getIdentityScope().clear();
    }

    public WordItemDao getWordItemDao() {
        return wordItemDao;
    }

}
